set D=-24 -l -d -oN
set DCLR_EXEC=yellow:exe,com,bat,cmd
set DCLR_ARC=brblue:zip,arj,rar,lzh,pak,zoo,arc,gz,tar
set DCLR_TEXT=white:txt,doc,diz,me,ans,nfo,asc
set DCLR_IMAGE=brred:jpg,gif,png,bmp,tif,tga,iff,lbm,pcx
set DCLR_CODE=cyan:c,h,cpp,hpp,pas,cc,asm,lib,obj
set DCLR_BAD=red:bak,$$$,old,tmp
set DCLR_SOUND=green:wav,mp3,mod,s3m,it,xm,mtm,669,mid,ptm,voc,mus,xmi,okt,amf
set DCLR_DIR=brcyan